on: [push, pull_request]
name: Test and lint

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm test

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@master

    - name: Install doctl
      uses: ./
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Verify installation
      run: doctl version

    - name: Verify log-in
      run: doctl compute region list

  test_custom_version_linux_and_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@master

    - name: Install doctl
      uses: ./
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        version: 1.38.0

    - name: Verify installation of correct version
      run: |
        VERSION=$(doctl version | head -1 | cut -f3 -d' ' | cut -f1 -d'-')
        if [ "$VERSION" != "1.38.0" ]; then exit 1; fi

    - name: Verify log-in
      run: doctl compute region list

  test_custom_version_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Install doctl
      uses: ./
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        version: 1.38.0

    - name: Verify installation of correct version
      run: |
        $VERSION = (doctl version | head -1 | cut -f3 -d' ' | cut -f1 -d'-')
        If (-NOT  ($VERSION -eq "1.38.0")) { exit 1 }

    - name: Verify log-in
      run: doctl compute region list
